# Generated by Django 3.1.7 on 2022-05-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='patient',
        ),
    ]
