# Generated by Django 3.2.2 on 2022-05-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0006_point'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Point',
        ),
    ]
